version: '2'

services:
  mariadb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-dump.sql:/docker-entrypoint-initdb.d/mysql-dump.sql:ro
    expose:
      - 3306
    networks:
      - shop-network
    restart: always

  prestashop:
    image: prestashop/prestashop:1.7.8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:443
    depends_on:
      - mariadb
    volumes:
      - ./prestadata:/var/www/html
      - ./prestadata/modules:/var/www/html/modules
      - ./prestadata/themes:/var/www/html/themes
      - ./prestadata/override:/var/www/html/override
      - ./certs/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./certs/localhost.crt:/usr/local/share/ca-certificates/localhost.crt
    environment:
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: localhost:8090
      PS_DOMAIN_SSL: ${PS_DOMAIN_SSL:-localhost:8090}
      PS_ENABLE_SSL: 1
      PS_SSL_ENABLED_EVERYWHERE: 1
    networks:
      - shop-network
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - 8081:80
    depends_on:
      - mariadb
    networks:
      - shop-network
    restart: always

networks:
  shop-network:
    driver: bridge
