<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWza1riy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWza1riy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerWza1riy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerWza1riy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerWza1riy\appProdProjectContainer([
    'container.build_hash' => 'Wza1riy',
    'container.build_id' => '3c9e4fa1',
    'container.build_time' => 1731869449,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWza1riy');
