<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xbxge9\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xbxge9/appProdProjectContainer.php') {
    touch(__DIR__.'/Container5xbxge9.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container5xbxge9\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container5xbxge9\appProdProjectContainer([
    'container.build_hash' => '5xbxge9',
    'container.build_id' => '2ba23e3b',
    'container.build_time' => 1731871612,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xbxge9');
