<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3grgvxh\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3grgvxh/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3grgvxh.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3grgvxh\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3grgvxh\appProdProjectContainer([
    'container.build_hash' => '3grgvxh',
    'container.build_id' => '9b5b6cbd',
    'container.build_time' => 1729638932,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3grgvxh');
